### ISSUE TITLE
Runnig and Testing locally

### ISSUE THREAD

**Issue by zowhair** [rahmonov/alcazar#1]
I have cloned this framework and want to build it locally and try to contribute. So after cloning it locally how can I run this framework without using pip install alcazar-... for example in first and second blog we were running this like, gunicorn app:app. Now how to do it at this level.

**Comment by rahmonov** [comment]
Hey @zowhair. You can do that by cloning the project and creating a file `app.py` in the project root. That way, you can easily import the framework like this from the `app.py`: 
`from alcazar import Alcazar`

**Comment by zowhair** [comment]
Okay Thanks Bro! 
I will let you know if any.
